# Generated by Django 5.2.7 on 2025-10-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='head',
            new_name='name',
        ),
    ]
