# Generated by Django 5.2.7 on 2025-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_head_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('drive_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='head',
        ),
    ]
