# Generated by Django 5.2.7 on 2025-10-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_topic_rename_name_product_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subtitle',
        ),
    ]
