# Generated by Django 5.2.7 on 2025-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_topic_title_remove_topic_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic_title',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
