# Generated by Django 5.2.7 on 2025-10-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_topic_title_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_title',
            old_name='title',
            new_name='description',
        ),
    ]
