# Generated by Django 5.2.8 on 2025-12-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pagevisit_delete_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
