# Generated by Django 5.2.8 on 2025-12-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile_ban_date_userprofile_ban_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ban_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='banned_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='suspension_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='suspension_start',
        ),
    ]
